//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Orders = new HashSet<Order>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int productid { get; set; }
        [Required(ErrorMessage ="Shkruani emrin e librit !")]
        public string name { get; set; }
        public string shortdescription { get; set; }
        public string longdescription { get; set; }
        [Required(ErrorMessage = "Shkruani emrin e autorit !")]
        public string autori { get; set; }
        [Required(ErrorMessage = "Vendosni cmimin!")]
        public decimal price { get; set; }
        public string imageurl { get; set; }
        public int isbookoftheweek { get; set; }
        public int categoryid { get; set; }
        public string filepreview { get; set; }
        [Required(ErrorMessage = "Shkruani sasine e disponueshme!")]
        public Nullable<int> sasidisponueshme { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
