//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int idkoment { get; set; }
        public int bookid { get; set; }
        public string userid { get; set; }
        public string commentdescription { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<System.DateTime> commentdate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Books Book { get; set; }
    }
}
