//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int idorderdetail { get; set; }
        public int idorder { get; set; }
        public Nullable<decimal> cmimtotalxprodukt { get; set; }
        public Nullable<int> sasiperprodukt { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
